# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ jethome ]
    tags: [ jethome_release_* ]
  pull_request:
    branches: [ jethome ]
    tags: [ jethome_release_* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Fix Permitions
      run: sudo chown -R actions:actions /home/actions/actions-runner/_work/

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set JETHOME_CI_REPO_BUILD_TYPE variable 
      run: |
       if [[ "$GITHUB_REF" = refs/tags/jethome_release_* ]]; then \
         echo '::set-env name=JETHOME_CI_REPO_BUILD_TYPE::release/debs'; \
       else \
         echo '::set-env name=JETHOME_CI_REPO_BUILD_TYPE::beta'; \
       fi

    # Compile
    - name: Run a one-line script
      run: ./compile_and_convert_to_jXXX.sh

    - name: Upload img J100
      run: |
       rsync -a output/images/Armbian_*_j100.img repo@update.jethome.ru:/var/www/update.jethome.ru/armbian/
       rsync -a output/images/Armbian_*_j80.img repo@update.jethome.ru:/var/www/update.jethome.ru/armbian/
       
    - name: Upload deb to repo
      run: rsync -ar --delete-before output/debs/ repo@update.jethome.ru:~/$JETHOME_CI_REPO_BUILD_TYPE/
